CREATE TABLE [dbo].[Emprunt]
(
	[Id] BIGINT IDENTITY PRIMARY KEY NOT NULL, 
    [LivreId] BIGINT NOT NULL, 
    [PersonneId] BIGINT NOT NULL, 
    [DateEmprunt] DATETIME NOT NULL, 
    [DateRetour] DATETIME NOT NULL 
    CONSTRAINT FK_LIVRE_TO_EMPRUNT FOREIGN KEY (LivreId) REFERENCES Livre(Id),
    CONSTRAINT FK_PERSONNE_TO_EMPRUNT FOREIGN KEY (PersonneId) REFERENCES Personne(Id),
)
